version: '2'
services:
  db:
    build: ./db
    ports:
     - "27017:27017"
    volumes:
     - "./db/data:/data/db"
     - "./db/scripts/create_user.js:/create_user.js"
    command: >
             sh -c '
             sh -c "mongod &"
             && sleep 2
             && mongo < /create_user.js
             && mongod --shutdown
             && mongod --auth
             '
    networks:
      tars_net:
        ipv4_address: 177.10.0.12
        ipv6_address: 2001:3984:3979::10

  front:
    build: ./front
    ports:
      - "80:80"
    volumes:
      - "./front/src/:/data/src/"
      - "./front/conf:/etc/nginx/sites-available"
      - "./front/scripts:/data/scripts"
    depends_on :
      - api
    command: bash -c "/data/scripts/start.sh"
    networks:
        tars_net:
          ipv4_address: 177.10.0.10
          ipv6_address: 2001:3984:3989::10


  api:
    build: ./api
    ports:
      - "1337:1337"
    volumes:
      - "./api/src:/data/src"
      - "./api/scripts:/data/scripts"
    command: >
            sh -c 'echo "AM GOING TO SLEEP"
            && sleep 2
            && bash -c "/data/scripts/start.sh"';
    environment: 
      NODE_ENV: development
    depends_on :
      - db
    networks:
        tars_net:
          ipv4_address: 177.10.0.11
          ipv6_address: 2001:3984:3969::10

networks:
  tars_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: 177.10.0.0/24
        gateway: 177.10.0.1
      - subnet: 2001:3984:3989::/64
        gateway: 2001:3984:3989::1
